route:
  group_by: ['notif']
  repeat_interval: 3h
  receiver: 'devops'
receivers:
  - name: 'devops'
    slack_configs:
    - channel: alerts 
      send_resolved: true 
      api_url:  https://hooks.slack.com/services/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
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
      text: >-
        {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
        {{ end }}
