global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codetab-monitor'


rule_files:
 - 'prometheus.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval:     5s
    static_configs:
    - targets: ['127.0.1.1:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
    - targets: ['127.0.1.1:9100']
      labels:
        group: 'ubuntu'
